### PR TITLE
Added placeholders for asset/3d view

### PR DESCRIPTION
**Pull request by ghost**
Adds a placeholder when an asset is not selected so the user is not looking at just spinning wheels

Fixes 3D loading dialog

### CODE REVIEW

**Review by anderscognite — COMMENTED** [review]
This PR seems much bigger than it needs to be? Could it easily be split into multiple, smaller PR's?

**Comment by cognite-cicd** [comment]
[pr-server]
View this change on [PR Server](https://pr-46.discovery.preview.cogniteapp.com)

**Comment by dlcognite** [comment]
@anderscognite removed AssetBreadcrumbs and added to another PR

**Comment by cognite-cicd** [comment]
[pr-server]
View this change on [PR Server](https://pr-46.discovery.preview.cogniteapp.com)

**Comment by cognite-cicd** [comment]
[pr-server]
View this change on [PR Server](https://pr-46.discovery.preview.cogniteapp.com)

**Comment by cognite-cicd** [comment]
[pr-server]
View this change on [PR Server](https://pr-46.discovery.preview.cogniteapp.com)

**Comment by cognite-cicd** [comment]
[pr-server]
View this change on [PR Server](https://pr-46.discovery.preview.cogniteapp.com)

**Comment by cognite-cicd** [comment]
[pr-server]
View this change on [PR Server](https://pr-46.discovery.preview.cogniteapp.com)

**Pull request merged**
