### PR TITLE
[CONTEXT-266] PNID file chain loading (moving from one file to the next based on PNID)

### PR DESCRIPTION
**Pull request by ghost**
Clicking on a PNID file will load in the document. As well added forward and back button for navigating between files.

Allow for clicking on one PNID to load another PNID if a file_id metadata is provided.

Demo: https://drive.google.com/open?id=1vbZ--ahV8wSjd_ArCBvM5qo5rZ4ODP01

### CODE REVIEW

**Review by waddahCog — CHANGES_REQUESTED** [review]
I don't think lines 143 5o 150 should be searching. 
Instead, I would files.list (we can't risk this being wrong) and remove the .svg tag from 'name'  parameter

I will ensure the the tag is added when generating the svg and try my best to get a tag that could be listed. Seems more safe.

**Comment by dlcognite** [comment]
@waddahCog changed to `list` instead :)

**Comment by anderscognite** [comment]
Great :) Remember to delete the branch after merge!

**Comment by waddahCog** [comment]
Done!

**Pull request merged**
