### PR TITLE
Added VX Viewer

### PR DESCRIPTION
**Pull request by ghost**
image
image

### CODE REVIEW

**Comment by dlcognite** [comment]
also fixes https://cognitedata.atlassian.net/browse/CONTEXT-264

**Comment by dlcognite** [comment]
Video: https://drive.google.com/file/d/16aMW_B2Hb89jNEhXLyX8eZU-g22Vg2j0/view?usp=sharing

**Review by anderscognite — APPROVED** [review]
Aren't the types on `npm`?

**Comment by dlcognite** [comment]
they are sadly not on npm :'( i copied it and modified from a random gist

**Pull request merged**
